Repository sociomantic-tsunami/git-hub, pull requests merged in 2022-01, with the labels that each got.

#298 Fix typos
  git-hub
  man.rst
Labels: part-doc

#303 README: Update Debian badge
  README.rst
  relnotes/typos.bug.md
Labels: type-enhancement, part-doc

#308 Add a workaround for GH checkout action
  .github/workflows/ci.yml
Labels: type-bug

#311 Fix error reading template from path
  git-hub
  relnotes/issue-310.bug.md
Labels: type-bug

#305 Remove unused import
  git-hub
Labels: tech-debt

#306 Fix name error in issue update --edit
  git-hub
  relnotes/issue-304.bug.md
Labels: type-bug

#312 Fix regression in `issue update`
  git-hub
  relnotes/issue-304.bug.md
  relnotes/issue-update-regressions.bug.md
Labels: type-bug, prio-high

#313 Fix pull new broken by #306
  git-hub
Labels: type-bug

#314 Remove old relnotes and add Ubuntu package badge
  README.rst
  relnotes/issue-310.bug.md
  relnotes/issue-update-regressions.bug.md
Labels: tech-debt
